package com.github.gamekinger1st.imitationcoreapi.api.diagnostic;

public enum ImitationDiagnosticCategory {
    ACTION_REJECTED,
    COMPATIBILITY_DEGRADED,
    UNSUPPORTED_RENDERER,
    MISSING_GECKOLIB_BRIDGE,
    MISSING_TENSURA_BRIDGE,
    INVALID_SNAPSHOT,
    UNSAFE_PERFECT_FORM,
    NO_SELECTED_FORM,
    REPLICA_UNSUPPORTED,
    FACTION_RESOLVER_MISSING,
    TEMPORARY_CLEANUP_FAILED,
    CLIENT_PROTOCOL_MISMATCH
}
