package com.github.gamekinger1st.imitationcoreapi.api.event;

public enum TransformationEventType {
    SNAPSHOT_CAPTURED,
    SNAPSHOT_STORED,
    SESSION_CREATED,
    SESSION_UPDATED,
    SESSION_TRANSITIONED,
    TRANSFORMATION_VALIDATED,
    TRANSFORMATION_APPLIED,
    REVERSION_REQUESTED,
    REVERSION_COMPLETED,
    RECOVERY_REQUIRED,
    CLEANUP_REQUESTED,
    CLEANUP_COMPLETED,
    TEMPORARY_STATE_ADDED,
    TEMPORARY_STATE_UPDATED
}
